In [1]:
import pygame
import numpy as np
import numpy.linalg as lin
import sys
import importlib
import itertools
import time

import Clipping
from Geometry import *
from camera import Camera
from draw import *

pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:

importlib.reload(Clipping)
importlib.reload(sys.modules['Geometry'])
from Geometry import *

importlib.reload(sys.modules['camera'])
from camera import Camera

importlib.reload(sys.modules['draw'])
from draw import *




In [3]:
def vert_list_to_lines(verts,cycle=True):
    cycle_edges = np.stack((verts,np.roll(verts,1,axis=0))).transpose([1,0,2])
    if cycle and len(verts) > 2:
        return cycle_edges
    else:
        return cycle_edges[:-1]
    
square = np.array([[1,1,0],[-1,1,0],[-1,-1,0],[1,-1,0]])
square1 = square + np.array([0,0,-1])
square2 = square + np.array([0,0,1])
connect = np.array([[[1,1,-1],[1,1,1]],[[-1,1,1],[-1,1,-1]],[[-1,-1,-1],[-1,-1,1]],[[1,-1,-1],[1,-1,1]]])
cube_lines_test = 2*np.concatenate((np.concatenate(list(map(vert_list_to_lines,[square1,square2]))),connect))

In [6]:
from colors import *
    
d = 4
cube_face_colors = [RED,YELLOW,GREEN,CYAN,MAGENTA, WHITE]
tess_face_colors = cube_face_colors + [ORANGE,PURPLE]

cube_shape = build_cube(d)


if d == 4:
    for face, color in zip(cube_shape.faces,tess_face_colors):
        face.color = color
    shapes = []
    for i in range(4):
        cube = cube_shape.copy()
        cube.update(pos = 2*np.eye(d)[i])
        shapes.append(cube)
        cube = cube_shape.copy()
        cube.update(pos = -2*np.eye(d)[i])
        shapes.append(cube)
    
    shapes = [cube_shape]
    cube_shape.transparent = True
if d == 3:
    for face, color in zip(cube_shape.faces,cube_face_colors):
        face.color = color
    cube1 = cube_shape.copy()
    cube1.update(pos=np.array([2,0,0]))

    cube2 = cube_shape.copy()
    cube2.update(pos=np.array([-2,0,0]))

    cube3 = cube_shape.copy()
    cube3.update(pos=np.array([0,0,2]))

    cube4 = cube_shape.copy()
    cube4.update(pos=np.array([0,0,-2]))

    cube5 = cube_shape.copy()
    cube5.update(pos=np.array([0,-2,0]))
    
    shapes = [cube1,cube2,cube3,cube4,cube5]
for i,shape in enumerate(shapes):
    shape.name = 'shape ' + str(i)

shape_combinations = list(itertools.combinations(shapes,2))

In [7]:

t = 0
size = width, height = 1100, 700

pygame.init()

if d == 3:
    draw_class = DrawOpenGL2D(pygame,size,draw_origin=np.zeros([d-1]))
    camera = Camera(pos = np.array([0.8,2,0.8]),draw_class = draw_class)
    camera.update_rot_matrix(0,-1,-3*np.pi/4)
    camera.update_rot_matrix(1,-1,-np.pi/4)
if d == 4:
    draw_class = DrawOpenGL3D(pygame,size,
                              draw_origin=np.array([0.0,0.0,-15.0]),
                              focal=4)
    draw_class.view_radius = 4
    #draw_class.stereo_view_angles = [[-30,0],[0,0]]
    camera = Camera(pos = np.array([0,0,0,0]),draw_class = draw_class)
    #camera.look_at(np.array([2,2,2,2]))
    #camera = Camera(pos = np.array([0.8,2,0.8,0.8]),draw_class = draw_class)
    #camera.update_rot_matrix(0,-1,-3*np.pi/4)
    #camera.update_rot_matrix(2,-1,-np.pi/4)
    #camera.update_rot_matrix(1,-1,-np.pi/4)
#camera.update_rot_matrix(2,3,-np.pi/4)
camera.clipping = True
quit = False
redraw = True
timer = time.time()
i = 0
while not quit:
    
    if redraw:
        draw_class.draw(camera,shapes)
        if d == 4:
            #draw_class.draw_lines_3d(cube_lines_test,GREEN,draw_origin = draw_class.draw_origin + )
            #draw_class.draw_lines_3d(cube_lines_test,GREEN)

            True
        pygame.display.flip()
        redraw = False
    
    events = pygame.event.get()
    
    redraw = camera.update(draw_class,events) #this is here so that we draw on the first frame
    
    for event in events:
        if event.type == pygame.QUIT:
            quit = True
        if event.type == pygame.KEYUP:
            if event.key == pygame.K_t:
                shapes[0].transparent = not shapes[0].transparent
                redraw = True
                print('transparency',shapes[0].transparent)
    keys = pygame.key.get_pressed()
    if keys[pygame.K_ESCAPE]:
        quit = True
    
    i = i+1
    if i > 30 and True:
        #print('redraw:',redraw)
        fps = 30/(time.time() - timer)
        if fps < 60:
            print(fps,'fps')
        timer = time.time()
        i = 0
pygame.quit()
print('game terminated')

36.233508642197144 fps
transparency False
53.44072234456193 fps
51.69305702708821 fps
52.14422290350413 fps
52.88755547074583 fps
54.46909897013161 fps
54.47994731648772 fps
53.73592640992133 fps
53.97092935476344 fps
53.93285242191619 fps
53.0565026399832 fps
55.21986507177579 fps
53.94353444727961 fps
57.824580236934004 fps
55.53025742777 fps
44.87355219997133 fps
44.48946890170386 fps
49.42511235915335 fps
46.068235504312135 fps
50.93813784443093 fps
47.23111427246947 fps
45.02601636664022 fps
51.77656627985876 fps
45.57432636777359 fps
game terminated


In [237]:
pygame.quit()

In [55]:
np.

2

In [263]:
#test minor extraction
verts = np.array([[1,0,0],[0,1,0],[1,1,0]])
dvs = verts - np.roll(verts,1,axis=0)
print(dvs[:-1])
dvs[:2][:,[0,2]]

[[ 0 -1  0]
 [-1  1  0]]


array([[ 0,  0],
       [-1,  0]])

In [5]:
False ^ True

True