# init

In [1]:
import pygame
import numpy as np
import numpy.linalg as lin
import sys
import importlib
import itertools
import time

import Clipping

import Geometry
from Geometry import Point
from camera import Camera
import draw
import vec
from inputs import input_update

# reload modules

In [121]:

importlib.reload(Clipping)
importlib.reload(Geometry)
importlib.reload(sys.modules['vec'])
importlib.reload(sys.modules['util'])
importlib.reload(sys.modules['opengl_draw_2d'])
importlib.reload(sys.modules['opengl_draw_3d'])
import Geometry

importlib.reload(sys.modules['camera'])
from camera import Camera
importlib.reload(sys.modules['inputs'])
from inputs import input_update

importlib.reload(sys.modules['draw'])
import draw



# build shapes

In [123]:
from colors import *
    
d = 3 #set dimensionality
cube_face_colors = [RED,YELLOW,GREEN,CYAN,MAGENTA, WHITE]
tess_face_colors = cube_face_colors + [ORANGE,PURPLE]

cube_shape = Geometry.build_cube(d)

#draw a pair of cubes for each axis
for face, color in zip(cube_shape.faces,tess_face_colors):
    face.color = color
shapes = []
r = 4
for i in range(d):
    cube = cube_shape.copy()
    cube.update(pos = r*np.eye(d)[i])
    shapes.append(cube)
    cube = cube_shape.copy()
    cube.update(pos = -r*np.eye(d)[i])
    shapes.append(cube)
#shapes = shapes[:2] + shapes[-4:] 
#shapes = shapes[:2] + shapes[-2:]
#shapes.pop(2) #removes top cube
#cube_shape.transparent = True
    
for i,shape in enumerate(shapes):
    shape.name = 'shape ' + str(i)

In [124]:
d = 3
sphere_shape = Geometry.build_sphere_3d(r=1,phi_pts=10,theta_pts=5)
#shapes = [sphere_shape]
shapes.append(sphere_shape)

In [17]:
d = 4
m = 16; n = 16
cylinder_shape = Geometry.build_duocylinder(rs=[1,1],axes=[[0,1],[2,3]],n_circ_pts=[m,n])
#cylinder_shape.transparent = True
for i,face in enumerate(cylinder_shape.faces[:m]):
    face.color = ORANGE
    #face.color = (np.cos(2*np.pi*i/m)**2,np.sin(2*np.pi*i/m)**2,1)
    #face.color = ((i+1)%2,(i+1)%2,i%2)
for i,face in enumerate(cylinder_shape.faces[m:]):
    face.color = CYAN
    #face.color = (1,np.cos(2*np.pi*i/m)**2,np.sin(2*np.pi*i/m)**2)
    #face.color = ((i+1)%2,i%2,(i+1)%2)
    #face.color = ((i+1)%2,(i+1)%2,i%2)
shapes = [cylinder_shape]


# main loop

Would like draw.py to have clearer distinctions between the various spaces. The layers are
1. The d-dim local spaces that shape.verts_ref, ref_frame, and face.normal_ref etc live in
2. The d-dim world space that rotated, scaled and positioned shapes (and faces) and cameras live
3. The d-dim space rotated and translated wrt to a camera
4. The (d-1)-dim space that shapes are projected on to
5. The (d-1)-dim graphics backend (openGL)

It would be nice if we could organize code according to these layers.

Clipping happens in 2

Todo: 
- fix target shape clipping
- speed up /generalize floor drawing
- speed up clipping
- find a way to make the center obvious wrt objects in the view. does rotation help or hurt? how can one navigate with a rotating viewport?
- other points of reference at infinity
- a floor and ceiling
- implement cubinders, spherinders
- generalize face fuzz to all convex faces, invariant to edge order

In [24]:
import colors
import vec
def test_points(camera,pos):
    points = [ vec.Vec([np.cos(th),np.sin(th),0,0]) + pos for th in np.linspace(0,2*np.pi,200)]
    draw.draw_points(camera,points,colors.GREEN)

In [125]:
#does not draw before input / does not update camera properly?

t = 0
#size = width, height = 1100, 700
size = width, height = 1600, 900

pygame.init()

if d == 3:
    draw.init(d,size,focal=6,n_fuzz_points = 200)
    draw.view_radius = 7
    draw_view_height = 7
    draw.view_boundary = 'cylinder'
    camera = Camera(pos = Point([0,0,-10]))
    camera.target_shape = Geometry.build_3d_target()
    #camera.update_rot_matrix(0,-1,-3*np.pi/4)
    #camera.update_rot_matrix(1,-1,-np.pi/4)
    camera.look_at(vec.zero_vec(d))
    #camera.look_at(vec.zero_vec(d))
    #camera = Camera(pos = Point([0,0,0]))
if d == 4:
    draw.init(d,size,stereo=False,n_fuzz_points = 200)
    draw.view_boundary = 'sphere'
    if draw.stereo:
        draw.view_radius = 4
    else:
        draw.view_radius = 6
        draw.view_height = 4
    #camera = Camera(pos = Point([0,0,0,0]))
    draw.face_scales = [0.9]
    #draw_class.stereo_view_angles = [[-30,0],[0,0]]
    #camera = Camera(pos = Point([0,0,0,0]))
    camera = Camera(pos = vec.one_hot(d,-1)*(-5))
    camera.look_at(vec.zero_vec(d))
    #camera.update_rot_matrix(0,-1,-3*np.pi/4)
    #camera.update_rot_matrix(2,-1,-np.pi/4)
    #camera.update_rot_matrix(1,-1,-np.pi/4)
#camera.update_rot_matrix(2,3,-np.pi/4)
draw.clipping = True
quit = False
redraw = True
timer = time.time()
t0 = time.time()
frame = 0
try:
    while not quit:

        if redraw:
            draw.draw(camera,shapes+ [camera.target_shape])
            draw.draw_floor(5,-5,WHITE,camera,shapes)
            #test_points(camera,shapes[0].pos)
            #draw.draw_wireframe(camera,cylinder_shape,GRAY)
            #draw.draw_normals(camera,shapes[0],WHITE)
            pygame.display.flip()
            redraw = False
            
        #this is here so that we draw on the first frame
        redraw, quit = input_update(camera, shapes)
        #camera.update_rot_matrix(0, 2, camera.ang_speed/2)
        #shapes[0].rotate(0,2,0.01)
        redraw = True #redraw every loop. useful for assessing framerate


        delta_t = (time.time() - timer)
        if delta_t > 2:
        #if False:
            #print('redraw:',redraw)
            try:
                #fps = 30/(time.time() - timer)
                fps = frame/delta_t
            except:
                fps = 0
            #if fps < 60:
            print(fps,'fps')
            timer = time.time()
            frame = 0
        frame = frame+1
except:
    pygame.quit()
    print('game terminated')
    raise
pygame.quit()
print('game terminated')

init GL


C:\Users\kook\Documents\python\4d\4d-game\Clipping.py:246: RuntimeWarning: invalid value encountered in double_scalars
  tm = (-b - sqrt_discr)/(2*a)
C:\Users\kook\Documents\python\4d\4d-game\Clipping.py:247: RuntimeWarning: invalid value encountered in double_scalars
  tp = (-b + sqrt_discr)/(2*a)


13.145852457851767 fps
13.713223464549534 fps


C:\Users\kook\Documents\python\4d\4d-game\Clipping.py:247: RuntimeWarning: divide by zero encountered in double_scalars
  tp = (-b + sqrt_discr)/(2*a)
C:\Users\kook\Documents\python\4d\4d-game\Clipping.py:246: RuntimeWarning: divide by zero encountered in double_scalars
  tm = (-b - sqrt_discr)/(2*a)


11.754195658563123 fps


C:\Users\kook\Documents\python\4d\4d-game\Clipping.py:151: RuntimeWarning: invalid value encountered in greater_equal
  p0_safe = p0n >= th
C:\Users\kook\Documents\python\4d\4d-game\Clipping.py:152: RuntimeWarning: invalid value encountered in greater_equal
  p1_safe = p1n >= th


11.87628071984469 fps
11.87626810935908 fps
11.759876465759973 fps
10.93506890684328 fps
12.003081540632952 fps
10.562702082831095 fps
12.249950028265719 fps
transparency True
9.309992475301149 fps
transparency False
9.305388597866008 fps
9.6954477000408 fps
10.886663871302504 fps
15.672248068025855 fps
10.932585462784566 fps
9.309979423639952 fps
9.03131640317509 fps
8.000848299098593 fps
7.843819442528878 fps
7.9213727590109055 fps
7.422670195532068 fps
8.004553299536834 fps
8.245076734201984 fps
8.556094500524942 fps
8.90727254193519 fps
10.396866788954439 fps


C:\Users\kook\Documents\python\4d\4d-game\vec.py:93: RuntimeWarning: invalid value encountered in add
  return v1 * (1 - x) + v2 * x
C:\Users\kook\Documents\python\4d\4d-game\vec.py:93: RuntimeWarning: invalid value encountered in double_scalars
  return v1 * (1 - x) + v2 * x


11.407923022499709 fps
9.122402537045126 fps
8.725889819180795 fps
9.027037123754873 fps
8.730181189125183 fps
9.602405876228143 fps
9.402121016487147 fps
9.117963498066667 fps
7.917517677564341 fps
8.00083573039167 fps
7.9174859179389605 fps
7.760110805758513 fps
game terminated


In [188]:
pygame.quit()

# workspace

In [79]:
import vec
vec.norm(Vec([-5.55299282,  3.03433562]))

6.327947685764504

In [7]:
def check_normals(shape):
    def check_face(face):
        vertis = face.get_verts(shape)
        verts = [shape.verts_ref[vi] for vi in vertis]
        center = face.center
        dots = [vec.dot(v-face.center,face.normal_ref) for v in verts]
        return np.all(vec.isclose(dots,vec.zero_vec(len(dots))))
    return [check_face(face) for face in shape.faces]

In [119]:
from numpy.linalg import svd
def test(shape,face):
        verts_in_face = [shape.verts[vi] for vi in face.get_verts(shape)]
        rel_verts = [v - face.center for v in verts_in_face]
        #find vector perpendicular to all vertices
        return svd(np.array(rel_verts))
print(test(cylinder_shape,cylinder_shape.faces[5])[-1][-1])
print(cylinder_shape.faces[5].normal_ref)

[-0.         -0.         -0.70710678 -0.70710678]
[-5.65986790e-17  0.00000000e+00  7.07106781e-01  7.07106781e-01]


In [141]:
cylinder_shape.check_normals()

True

In [142]:
Clipping.clip_line_plane(Geometry.Line(Vec([0,0]),Vec([1,-3])),Geometry.HyperPlane(vec.one_hot(2,1),-2))

Line([0 0],[ 0.66666667 -2.        ])

In [52]:
from vec import Vec
test =Clipping.sphere_line_intersect(Geometry.Line(Vec([2,0]),Vec([-2,0])),4,return_ts=True)
print(test)

([array([4., 0.]), array([-4.,  0.])], (6.0, -2.0))


In [64]:
n_circ_pts = [3,4]
print([(j+i*n_circ_pts[1],(j+1)%n_circ_pts[1]+i*n_circ_pts[1])
        for i,j in itertools.product(range(n_circ_pts[0]),range(n_circ_pts[1]))])
[(j+i*n_circ_pts[1],j + ((i+1)%n_circ_pts[0])*n_circ_pts[1])
        for i,j in itertools.product(range(n_circ_pts[0]),range(n_circ_pts[1]))]

[(0, 1), (1, 2), (2, 3), (3, 0), (4, 5), (5, 6), (6, 7), (7, 4), (8, 9), (9, 10), (10, 11), (11, 8)]


[(0, 4),
 (1, 5),
 (2, 6),
 (3, 7),
 (4, 8),
 (5, 9),
 (6, 10),
 (7, 11),
 (8, 0),
 (9, 1),
 (10, 2),
 (11, 3)]

In [58]:
[(i,j) for i,j in itertools.product(range(n_circ_pts[0]),range(n_circ_pts[1]))]

[(0, 0),
 (0, 1),
 (0, 2),
 (0, 3),
 (1, 0),
 (1, 1),
 (1, 2),
 (1, 3),
 (2, 0),
 (2, 1),
 (2, 2),
 (2, 3)]

In [67]:
shapes[0].update(angles=[0,time.time()])

[[ 1.          0.          0.          0.        ]
 [ 0.         -0.97774833  0.         -0.20978138]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.20978138  0.         -0.97774833]]


In [68]:
time.time()

1556095332.9433315